### PR TITLE
chore: convert whitespaces to tabs

### PR DESCRIPTION
**Pull request by giautm**

### CODE REVIEW

**Review by a8m — APPROVED** [review]
Thanks for fixing this @giautm

**Comment by Allianzcortex** [comment]
awww @a8m ever consider adding auto-format/lint-detect tool ?

**Comment by giautm** [comment]
> awww @a8m ever consider adding auto-format/lint-detect tool ? 

Which tools will working with Go text/template? 🤔

**Comment by Allianzcortex** [comment]
@giautm you can absolutely find resouces here(e.g. https://github.com/sourcegraph/go-template-lint) If it cannot then we can create an issue with #TODO label to create a tool to do it. It should not be so hard.

**Comment by a8m** [comment]
> awww @a8m ever consider adding auto-format/lint-detect tool ?

You're welcome to help with that 😃

**Pull request merged**
