### PR TITLE
entql: add driver.Valuer to generated predicates

### PR DESCRIPTION
**Pull request by a8m**

### CODE REVIEW

**Review by BrentChesny — COMMENTED** [review]
I think the check for a UUID type also needs to happen for the `WhereID` predicate in entql.tmpl? Otherwise looks good to me!

**Comment by a8m** [comment]
> I think the check for a UUID type also needs to happen for the `WhereID` predicate in entql.tmpl? Otherwise looks good to me!

Good catch! Can you add it to this branch?

**Comment by BrentChesny** [comment]
> Can you add it to this branch?

Would be happy to. How can I add a commit to your PR though? Probably a stupid question, but I'm not used to working with PRs on github. 😄

**Comment by a8m** [comment]
Create a branch from my branch (entqlpred), add the commit there, and then create a PR from your branch to mine. Let me know if you need help with this.

**Comment by BrentChesny** [comment]
> Create a branch from my branch (entqlpred), add the commit there, and then create a PR from your branch to mine. Let me know if you need help with this.

Cool. Created #1006.

**Pull request merged**
