### PR TITLE
Make foreign key colume name back to `edgeName_id' style(reverse #286).

### LINKED ISSUE #548: o2o-recursive storage key for edge is kind of confusing
Per the o2o-recursive [example](https://entgo.io/docs/schema-edges/#o2o-same-type), `node_nex`t in db table actually means `node_prev`.

```
id	value	node_next
2	2	1
3	3	2
4	4	3
5	5	4
1	1	5
```

This change is introduced in #286.

### PR DESCRIPTION
**Pull request by kidlj**
To achive this goal this commit does following things:

- Introduces edge.ToFrom() to define bi-directional edges(o2obidi, m2mbidi), this kind of edges set the "Bidi: true" field early to indicate the bi-directional relationship.
- Make all other kind of relationships must have To() edge and From() edge both defined and paired.
- With the two constraints introduced above, an inverse edge isn't optional anymore and can not be dropped. So the `edgeName_id' kind Foreign key name won't change.

The purpose of disallowing From() edges to be dropped is to keep FK names unchanged.

The purpose of introducing ToFrom() edge is that before this commit, a bi-directional edge looks just like an To() edge only(although to the same type as the edge owner) and has no inverse edge defined, this violates the principle described above that a To() edge must have an inverse From() edge paired.

This commit fixes #548.

I also believe that with these changes, it will be easier to add better offline/edge migration support in the future.

### CODE REVIEW

**Comment by kidlj** [comment]
I know this is a big change to Ent, so feel free to ignore it if it violates the design principle of Ent. Thanks.

**Comment by kidlj** [comment]
The CI found a bug that maybe was caused by this commit, I tried to solve but cannot figure it out. Glad if someone can help to point it out.

```
$ go test -race -count=2 -tags='json1' ./...
--- FAIL: TestMaria (0.07s)
    enttest.go:67: sql/schema: drop index of table "field_types": Error 1553: Cannot drop index 'field_types_files_field': needed in a foreign key constraint
--- FAIL: TestMySQL (0.13s)
    --- FAIL: TestMySQL/57 (0.04s)
        enttest.go:67: sql/schema: drop index of table "field_types": Error 1553: Cannot drop index 'field_types_files_field': needed in a foreign key constraint
    --- FAIL: TestMySQL/8 (0.03s)
        enttest.go:67: sql/schema: drop index of table "field_types": Error 1553: Cannot drop index 'field_types_files_field': needed in a foreign key constraint
    --- FAIL: TestMySQL/56 (0.06s)
        enttest.go:67: sql/schema: drop index of table "field_types": Error 1553: Cannot drop index 'field_types_files_field': needed in a foreign key constraint
--- FAIL: TestMaria (0.08s)
    enttest.go:67: sql/schema: drop index of table "field_types": Error 1553: Cannot drop index 'field_types_files_field': needed in a foreign key constraint
--- FAIL: TestMySQL (0.44s)
    --- FAIL: TestMySQL/56 (0.10s)
        enttest.go:67: sql/schema: drop index of table "field_types": Error 1553: Cannot drop index 'field_types_files_field': needed in a foreign key constraint
    --- FAIL: TestMySQL/57 (0.17s)
        enttest.go:67: sql/schema: drop index of table "field_types": Error 1553: Cannot drop index 'field_types_files_field': needed in a foreign key constraint
    --- FAIL: TestMySQL/8 (0.16s)
        enttest.go:67: sql/schema: drop index of table "field_types": Error 1553: Cannot drop index 'field_types_files_field': needed in a foreign key constraint
FAIL
FAIL    github.com/facebook/ent/entc/integration        49.652s
ok      github.com/facebook/ent/entc/integration/config 0.040s
```

**Comment by kidlj** [comment]
The CI found a bug that maybe was caused by this commit, I tried to solve but cannot figure it out. Glad if someone can help to point it out.

```
2020-12-21T07:46:49.3666185Z Previous HEAD position was 0902673b entc/integ: add mariadb 10.2 to integrarion (#1070)
2020-12-21T07:46:49.3980289Z HEAD is now at 2b6d3724 Merge eb5a24fde71d4e52a4f77884013540ef726fd91c into 0902673b4024a93cf2abf5dac29eb45724503ff7
2020-12-21T07:46:49.4039489Z ##[group]Run go test -race -count=2 -tags='json1' ./...
2020-12-21T07:46:49.4040267Z [36;1mgo test -race -count=2 -tags='json1' ./...[0m
2020-12-21T07:46:49.4074942Z shell: /bin/bash -e {0}
2020-12-21T07:46:49.4075431Z ##[endgroup]
2020-12-21T07:47:22.8554424Z --- FAIL: TestMaria (0.03s)
2020-12-21T07:47:22.8555900Z     enttest.go:67: sql/schema: alter table "field_types": Error 1553: Cannot drop index 'field_types_files_field': needed in a foreign key constraint
2020-12-21T07:47:22.8556982Z --- FAIL: TestMySQL (0.16s)
2020-12-21T07:47:22.8557646Z     --- FAIL: TestMySQL/56 (0.04s)
2020-12-21T07:47:22.8558862Z         enttest.go:67: sql/schema: alter table "field_types": Error 1553: Cannot drop index 'field_types_files_field': needed in a foreign key constraint
2020-12-21T07:47:22.8559917Z     --- FAIL: TestMySQL/57 (0.05s)
2020-12-21T07:47:22.8561185Z         enttest.go:67: sql/schema: alter table "field_types": Error 1553: Cannot drop index 'field_types_files_field': needed in a foreign key constraint
2020-12-21T07:47:22.8562267Z     --- FAIL: TestMySQL/8 (0.06s)
2020-12-21T07:47:22.8563541Z         enttest.go:67: sql/schema: alter table "field_types": Error 1828: Cannot drop column 'file_field': needed in a foreign key constraint 'field_types_files_field'
2020-12-21T07:47:22.8564630Z --- FAIL: TestMaria (0.01s)
2020-12-21T07:47:22.8566048Z     enttest.go:67: sql/schema: alter table "field_types": Error 1553: Cannot drop index 'field_types_files_field': needed in a foreign key constraint
2020-12-21T07:47:22.8567102Z --- FAIL: TestMySQL (0.08s)
2020-12-21T07:47:22.8567764Z     --- FAIL: TestMySQL/56 (0.02s)
2020-12-21T07:47:22.8568969Z         enttest.go:67: sql/schema: alter table "field_types": Error 1553: Cannot drop index 'field_types_files_field': needed in a foreign key constraint
2020-12-21T07:47:22.8570022Z     --- FAIL: TestMySQL/57 (0.02s)
2020-12-21T07:47:22.8571295Z         enttest.go:67: sql/schema: alter table "field_types": Error 1553: Cannot drop index 'field_types_files_field': needed in a foreign key constraint
2020-12-21T07:47:22.8572283Z     --- FAIL: TestMySQL/8 (0.04s)
2020-12-21T07:47:22.8573433Z         enttest.go:67: sql/schema: alter table "field_types": Error 1828: Cannot drop column 'file_field': needed in a foreign key constraint 'field_types_files_field'
2020-12-21T07:47:22.8574265Z FAIL
```

**Comment by AlexanderMatveev** [comment]
This really confusing. Edge name is not even a part of column name.

```golang
func (User) Edges() []ent.Edge {
	return []ent.Edge{
		//...
		edge.To("streams", Stream.Type),
		//...
	}
}

func (Stream) Edges() []ent.Edge {
	return []ent.Edge{
		// ...
		edge.From("owner", User.Type).
			Ref("streams").
			Unique().
			Required(),
		// ...
	}
}```

Why this example gives "streams_users_streams" column name?

**Comment by a8m** [comment]
@AlexanderMatveev, please see the motivation for it here https://github.com/ent/ent/issues/548#issuecomment-643636090

You can use the `StorageKey` option on edges in order to configure this differently, or you can also use the [Edge Field](https://entgo.io/docs/schema-edges/#edge-field) option (together with `StorageKey`).

Also, this is going to be changed in the upcoming versions (next one or one after) as we'll provide a versioning option to the `ent.Schema`s.

**Comment by AlexanderMatveev** [comment]
@a8m thanks for response. I still just a little not agree with motivation to configure column name at `To` holder (`User` in my example), because there are still many cases when we have only `From` side and don't need any relations from `User`. But looks like there are reasons for this under the hood, so I obey 🙂 Anyway, `StorageKey` worked.

**Comment by kidlj** [comment]
Not to reopen this PR, just to leave a note to myself(the PR author).

> Make all other kind of relationships must have To() edge and From() edge both defined and paired.

After some more experiences with Ent, I finally figured out that in some scenarios we don't always want To() edge and From() Edge both defined and paired, for safety considerations or to avoid unnecessary accesses. So this assumption is not applicable. Now I'm happy to see this PR be buried deep under this great project.

**Pull request closed without merging**
