### PR TITLE
Make custom field comment render as additional line(s)

### PR DESCRIPTION
**Pull request by zzwx**
The intent is to keep originally generated comment that has the DB field name in it, and simply append the custom comments right below. Also ID field seemed to be ignoring the comment completely.

For those, who'd want to produce paragraph separation that simply means adding `\n` in front of the comment.

### CODE REVIEW

**Review by a8m — APPROVED** [review]
That makes sense. Thanks for addressing this @zzwx 

One small comment before I land this - you need to change [this test](https://github.com/facebook/ent/blob/master/entc/integration/config/config_test.go#L60-L66) to follow the new format (maybe use `Contains` instead of `Equals`).

**Comment by zzwx** [comment]
My bad, missed that test, also integration tests fail...

**Comment by a8m** [comment]
Thanks for your contribution @zzwx. It's appreciated!

**Comment by zzwx** [comment]
Thank you for walking me through the process!

**Pull request merged**
