### PR TITLE
entc/gen: fix indentation in runtime template

### PR DESCRIPTION
**Pull request by a8m**

### CODE REVIEW

**Comment by giautm** [comment]
hey @a8m ,

Spacing in this file have mixed between tabs and whitespace. Should we convert them to tabs ?

**Comment by giautm** [comment]
You can pick commit from 94092fd8113dbfc7a58fe014a9097e64ca56e9d2

**Comment by a8m** [comment]
> hey @a8m ,
> 
> Spacing in this file have mixed between tabs and whitespace. Should we convert them to tabs ?
> 

Sure, go ahead and create a PR. Thanks

**Comment by giautm** [comment]
> > hey @a8m ,
> > Spacing in this file have mixed between tabs and whitespace. Should we convert them to tabs ?
> 
> Sure, go ahead and create a PR. Thanks

Done, via: https://github.com/facebook/ent/pull/1060

**Pull request merged**
