### PR TITLE
Implement Other Field

### LINKED ISSUE #1105: Add field.Other type
Create `field.Other` for fields that do not fit inside standard types. E.g. postgres range or spatial types

- [x] I have searched the [issues](https://github.com/facebook/ent/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

Currently we often use String to map custom go types. E.g.

PostGis Example

Current 
```
field.String("point").
            GoType(&spatial.Point{}),
```

Desired
```
field.Other("point").
            GoType(&spatial.Point{}),
```

Postgres Range (Feels awkward)
```
field.String("daterange").
            GoType(&pgxtype.Tstzrange{}),
```

## Motivation 🔦

Other will not have any predicates
Other will error if the go type is missing
The String type will generate the normal predicates because the underlying type is expected to be a string type
E.g. `type Role string`

### PR DESCRIPTION
**Pull request by cliedeman**
Resolves #1105

### CODE REVIEW

**Comment by cliedeman** [comment]
split postgres specific integration tests into different PR #1151 to keep this one small

**Comment by a8m** [comment]
See me comment https://github.com/facebook/ent/pull/1151#issuecomment-761619630

**Comment by cliedeman** [comment]
@a8m Thanks done.

**Comment by a8m** [comment]
Thanks for updating the PR @cliedeman, I plan to review it this week. 
Can you also update the website documentation (see doc/md/schema-fields.md)?  Thanks

**Comment by cliedeman** [comment]
@a8m Thanks, just pushed the docs. Let me know if that is enough

**Comment by a8m** [comment]
Thanks for your contribution @cliedeman. This was merged with #1218

**Pull request closed without merging**
