### PR TITLE
entc/gen: fix typo in "MaskNotFound" func comment

### PR DESCRIPTION
**Pull request by ernado**
Found another typo ^^

Looks like after `go generate ./...` the `bindata.go` changed from ` os.FileMode(420)` to `os.FileMode(436)` which is weird, should I fix it?

### CODE REVIEW

**Comment by a8m** [comment]
Hey @ernado and thanks for fixing this.

Please re-run `go generate ./...` from the root of the project. Regarding binddata, I'm not sure what's the problem, but if you find some, feel free to send a patch.

**Comment by ernado** [comment]
```console
ernado@nexus:/src/ent$ go generate ./...
ernado@nexus:/src/ent$ git diff
```
I'm getting zero diff after running `go geneate ./...` in root and `git status` is not reporting any changed files :thinking:

**Comment by ernado** [comment]
Probably os.FileMode(420) is causing that issue, I'll investigate and ping you when pipeline is green again.

**Comment by ernado** [comment]
PTAL @a8m, I've fixed pipeline issues.

Note that I've updated bindata flags so this won't happen again for anyone.

**Comment by a8m** [comment]
Thanks for your contribution @ernado 😃

**Pull request merged**
